config/routes.rb
Rails.application.routes.draw do
 devise_for :admin, controllers: {
  sessions:      'admin/sessions/sessions',
  passwords:     'admin/sessions/passwords',
  registrations: 'admin/sessions/registrations'
}
 namespace :admin do
   resources :genres, only:[:index, :create, :edit, :update]
   resources :items, only:[:show, :index, :new, :create, :edit, :update]
   resources :customers, only:[:index, :show, :edit, :update]
   get "" => "homes#top"
   resources :orders, only:[:show, :update]
 end

 devise_for :customers, controllers: {
  sessions:      'public/customers/sessions',
  passwords:     'public/customers/passwords',
  registrations: 'public/customers/registrations'
}

 scope module: :public do
  resources :customers, only:[:show, :edit, :update] do
   collection do
    get 'check'
    patch 'withdrawal'
   end
  end
  resources :shipping_addresses, only:[:index, :create, :edit, :update, :destroy]
  resources :items, only:[:index, :show]
  resources :cart_items, only:[:index, :update, :create, :destroy] do
   collection do
    delete 'all_destroy'
   end
  end
  resources :orders, only:[:new, :index, :show, :create] do
   collection do
    post 'confirm'
    get 'thanks'
   end
  end
 end

 root to: 'public/homes#top'
 get 'about' => 'public/homes#about'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  def full_name
    self.last_name + self.first_name
  end

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + full_name
  end
  
  def active_for_authentication?
    super && (is_active == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  attachment :image

  def add_tax_price
    (self.price * 1.1).round
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum oder_status: { unpaid: 0, deposited: 1, producing: 2, preparation: 3, sent: 4 }

  def full_address
    '〒' + postal_code + ' ' + address
  end

  def itemtotal
    total_amount - postage
  end

  def total_count
   total = 0
	 order_items.each do |order_items|
	  total += order_items.amount
	 end
	 total
	end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum task_status: { pending: 0, waiting: 1, working: 2, completed: 3 }

  def subtotal
    sub_total * amount
  end

  def item_subtotal
    item.add_tax_price * amount
  end
  

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private
	def customer_params
	  params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number,:email,:is_active)
	end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def edit
     @item = Item.find(params[:id])
     @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total_price = 0
  end

  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  def after_sign_in_path_for(resource)
   if resource.instance_of?(Admin)
     admin_path
   elsif resource.instance_of?(Customer)
     root_path
   else
     root_path
   end
  end

  def after_sign_out_path_for(resource)
   if resource == :admin
     new_admin_session_path
   elsif resource == :customer
     root_path
   else
     root_path
   end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <h5 class="bg-light">　<%= @customer.full_name %>さんの会員情報編集　</h5>
  </div>
  <div class="row">
    <%= form_with model: @customer, url:admin_customer_path, local: true do |f| %>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th>名前 (性)</th>
          <th><%= f.text_field :last_name, autofocus: true %></th>
          <th>(名)</th>
          <th><%= f.text_field :first_name, autofocus: true %></th>
        </tr>
        <tr>
          <th>フリガナ (セイ)</th>
          <th><%= f.text_field :last_name_kana, autofocus: true %></th>
          <th>(メイ)</th>
          <th><%= f.text_field :first_name_kana, autofocus: true %></th>
        </tr>
        <tr>
          <th>郵便番号(ハイフンなし)</th>
          <th><%= f.text_field :postal_code, autofocus: true %></th>
        </tr>
        <tr>
          <th>住所</th>
          <th><%= f.text_field :address, autofocus: true %></th>
        </tr>
        <tr>
          <th>電話番号(ハイフンなし)</th>
          <th><%= f.text_field :telephone_number, autofocus: true %></th>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <th><%= f.email_field :email, autofocus: true, autocomplete: "email" %></th>
        </tr>
        <tr>
          <th><%= f.label :"会員ステータス" %></th>
          <th><%= f.select :is_active, {'有効': true, '退会': false} %></th>
        </tr>
        <tr>
          <th></th>
          <th><%= f.submit '変更保存', class:"btn btn-success" %></th>
        </tr>
      </tbody>
    </table>
  <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row">
  <h5 class="bg-light">　会員一覧　</h5>
  <table class="table">
   <thead>
    <tr>
     <th scope="col">会員ID</th>
     <th scope="col">氏名</th>
     <th scope="col">メールアドレス</th>
     <th scope="col">ステータス</th>
    </tr>
   </thead>
   <tbody>
    <% @customers.each do |customer| %>
    <tr>
     <td><%= customer.id %></td>
     <td><%= link_to customer.full_name, admin_customer_path(customer.id) %></td>
     <td><%= customer.email %></td>
     <td>
      <% if customer.is_active == true %>
      有効
      <% elsif customer.is_active == false %>
      退会
      <% end %>
     </td>
    </tr>
    <% end %>
   </tbody>
  </table>
  <%= paginate @customers %>
 </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <h5 class="bg-light">　<%= @customer.full_name %>さんの会員詳細　</h5>
  </div>
  <div class="row">
    <div class="col-md-5">
    <table class="table table-borderless">
     <tbody>
      <tr>
        <th>会員ID</th>
        <th><%= @customer.id %></th>
      </tr>
      <tr>
        <th>氏名</th>
        <th><%= @customer.last_name %> <%= @customer.first_name %></th>
      </tr>
      <tr>
        <th>フリガナ</th>
        <th><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></th>
      </tr>
      <tr>
        <th>郵便番号</th>
        <th><%= @customer.postal_code %></th>
      </tr>
      <tr>
        <th>住所</th>
        <th><%= @customer.address %></th>
      </tr>
      <tr>
        <th>電話番号</th>
        <th><%= @customer.telephone_number %></th>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <th><%= @customer.email %></th>
      </tr>
      <tr>
        <th>ステータス</th>
        <th>
         <% if @customer.is_active == true %>
           有効
         <% elsif @customer.is_active == false %>
          退会
         <% end %>
        </th>
      </tr>
      <tr>
        <th>
          <%= link_to "編集する", edit_admin_customer_path(@customer.id),class:"btn btn-success" %>
        </th>
        <th>
          <%= link_to "注文一覧を見る", admin_path,class:"btn btn-primary" %>
        </th>
      </tr>
     </tbody>
    </table>
    </div>
  </div>
</div>

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <h5 class="bg-light">　ジャンル編集　</h5>
  </div>
  <p></p>
  <div class="row">
    <div class="col-md-6">
     <%= form_with model:@genre,url:admin_genre_path(@genre), local:true do |f| %>
       ジャンル名
       <%= f.text_field :name %>
       <%= f.submit '変更を保存',class:"btn btn-success" %>
     <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <h5 class="bg-light">　ジャンル一覧・追加　</h5>
  </div>
  <p></p>
  <div class="row">
    <div class="col-md-6">
     <%= form_with model:@genre,url:admin_genres_path, local:true do |f| %>
       ジャンル名
       <%= f.text_field :name %>
       <%= f.submit '新規登録',class:"btn btn-success" %>
     <% end %>
    </div>
  </div>
  <p></p>
  <div class="row">
    <div class="col-md-3">
     <table class="table">
       <thead>
         <tr>
           <th>ジャンル</th>
           <th></th>
         </tr>
       </thead>
       <tbody>
         <% @genres.each do |genre| %>
         <tr>
           <td>
             <%= genre.name %>
           </td>
           <td>
             <%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success"  %>
           </td>
         </tr>
         <% end %>
       </tbody>
     </table>
    </div>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
 <div class="row">
  <h5 class="bg-light">　注文履歴一覧　</h5>

<table class="table">
 <thead>
  <tr>
   <th scope="col">購入日時</th>
   <th scope="col">購入者</th>
   <th scope="col">注文個数</th>
  </tr>
 </thead>
 <tbody>
  <% @orders.each do |order| %>
  <tr>
    <td><%= link_to order.created_at.strftime('%Y/%m/%d'), admin_order_path(order.id) %></td>
    <td><%= order.customer.full_name %></td>
    <td><%= order.total_count %></td>
  </tr>
  <% end %>
 </tbody>
</table>
 </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
   <h5 class="bg-light">　商品編集　</h5>
  </div>
  <div class="row">
   <%= form_with model:@item,url:admin_item_path, local:true do |f| %>
   <table class="table table-borderless">
    <tbody>
     <tr>
      <th>商品画像</th>
      <th><%= f.attachment_field :image %></th>
     </tr>
     <tr>
      <th>商品名</th>
      <th><%= f.text_field :name %></th>
     </tr>
     <tr>
      <th>商品説明</th>
      <th><%= f.text_area :introduction %></th>
     </tr>
     <tr>
      <th>ジャンル</th>
      <th><%= f.collection_select :genre_id, @genres, :id, :name %></th>
     </tr>
     <tr>
      <th>税抜価格</th>
      <th><%= f.text_field :price %></th>
     </tr>
     <tr>
      <th>販売ステータス</th>
      <th><%= f.select :is_active, {'販売中': true, '売り切れ': false}, { include_blank: '選択してください'} %></th>
     </tr>
     <tr>
      <th></th>
      <th><%= f.submit '変更保存', class:"btn btn-success" %></th>
     </tr>
    </tbody>
   </table>
  <% end %>
  </div>
 </div>

app/views/admin/items/index.html.erb
<div class="container">
 <div class="row">
  <h5 class="bg-light">　商品一覧　</h5>
  <table class="table">
   <thead>
    <tr>
     <th scope="col">商品ID</th>
     <th scope="col">商品名</th>
     <th scope="col">税抜価格</th>
     <th scope="col">ジャンル一覧</th>
     <th scope="col">ステータス</th>
    </tr>
   </thead>
   <tbody>
    <% @items.each do |item| %>
    <tr>
     <td><%=item.id %></td>
     <td>
      <%= link_to admin_item_path(item.id) do %>
       <%=item.name %>
      <% end %>
     </td>
     <td><%=item.price.to_s(:delimited) %></td>
     <td><%=item.genre.name %></td>
     <td>
      <% if item.is_active == true %>
       販売中
      <% elsif item.is_active == false %>
       販売停止中
      <% end %>
     </td>
    </tr>
    <% end %>
   </tbody>
  </table>
  <%= paginate @items %>
 </div>
</div>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
<%= form_with model:@item,url:admin_items_path, local:true do |f| %>

  <h4>商品画像</h4>
  <%= f.attachment_field :image %>

  <h4>商品名</h4>
  <%= f.text_field :name %>

  <h4>商品説明</h4>
  <%= f.text_area :introduction %>

  <h4>ジャンル</h4>
  <%= f.collection_select :genre_id, @genres, :id, :name %>

  <h4>税抜価格</h4>
  <%= f.text_field :price %>

  <h4>販売ステータス</h4>
  <%= f.select :is_active, {'販売中': true, '売り切れ': false}, { include_blank: '選択してください'} %>

  <%= f.submit '新規登録' %>

<% end %>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <h5 class="bg-light">　商品詳細　</h5>
  </div>
  <p></p>
  <div class="row">
    <div class="col-md-4">
     <%= attachment_image_tag(@item, :image, size: "300x220") %>
    </div>
    <div class="col-md-8">
     <table class="table table-borderless">
      <tbody>
       <tr>
        <th>商品名</th>
        <th><%= @item.name %></th>
       </tr>
       <tr>
        <th>商品説明</th>
        <th><%= @item.introduction %></th>
       </tr>
       <tr>
        <th>ジャンル</th>
        <th><%= @item.genre.name %></th>
       </tr>
       <tr>
        <th>税込価格<br>(税抜価格)</th>
        <th><%= @item.add_tax_price.to_s(:delimited) %> (<%= @item.price.to_s(:delimited) %>) 円</th>
       </tr>
       <tr>
        <th>販売ステータス</th>
        <th>
         <% if @item.is_active == true %>
          販売中
         <% elsif @item.is_active == false %>
          販売停止中
         <% end %>
        </th>
       </tr>
       <tr>
        <th></th>
        <th>
         <%= link_to "編集する", edit_admin_item_path(@item), class:"btn btn-success" %>
        </th>
       </tr>
      </tbody>
     </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <h5 class="bg-light">　注文履歴詳細</h5>
  </div>
  <div class="row">
    <div class="col-md-5">
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th>購入者</th>
          <th><%= @order.customer.full_name %></th>
        </tr>
        <tr>
          <th>注文日</th>
          <th><%= @order.created_at.strftime('%Y/%m/%d') %></th>
        </tr>
        <tr>
          <th>配送先</th>
          <th>〒<%= @order.postal_code %> <%= @order.address %><br><%= @order.name %></th>
        </tr>
        <tr>
          <th>支払い方法</th>
          <th><%= @order.payment_method_i18n %></th>
        </tr>
      </tbody>
    </table>
    </div>
  </div>
  <p></p>
  <div class="row">
    <div class="col">
      <table class="table">
       <thead>
        <tr>
          <th>商品名</th>
          <th>単価(税込)</th>
          <th>数量</th>
          <th>小計</th>
        </tr>
       </thead>
       <tbody>
        <% @order_items.each do |order_item| %>
        <tr>
          <td><%= order_item.item.name %></td>
          <td><%= order_item.item.add_tax_price.to_s(:delimited) %></td>
          <td><%= order_item.amount %></td>
          <td><%= order_item.subtotal.to_s(:delimited) %><% @total_price += order_item.subtotal %></td>
        </tr>
        <% end %>
       </tbody>
     </table>
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-3">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>商品合計</th>
            <th><%= @order.itemtotal.to_s(:delimited) %></th>
          </tr>
          <tr>
            <th>送料</th>
            <th><%= @order.postage.to_s(:delimited) %>円</th>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <th><%= @order.total_amount.to_s(:delimited) %>円</th>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>