config/routes.rb
Rails.application.routes.draw do
 devise_for :admin, controllers: {
  sessions:      'admin/sessions/sessions',
  passwords:     'admin/sessions/passwords',
  registrations: 'admin/sessions/registrations'
}
 namespace :admin do
   resources :genres, only:[:index, :create, :edit, :update]
   resources :items, only:[:show, :index, :new, :create, :edit, :update]
   resources :customers, only:[:index, :show, :edit, :update]
   get "" => "homes#top"
   resources :orders, only:[:show, :update]
 end

 devise_for :customers, controllers: {
  sessions:      'public/customers/sessions',
  passwords:     'public/customers/passwords',
  registrations: 'public/customers/registrations'
}

 scope module: :public do
  resources :customers, only:[:show, :edit, :update] do
   collection do
    get 'check'
    patch 'withdrawal'
   end
  end
  resources :shipping_addresses, only:[:index, :create, :edit, :update, :destroy]
  resources :items, only:[:index, :show]
  resources :cart_items, only:[:index, :update, :create, :destroy] do
   collection do
    delete 'all_destroy'
   end
  end
  resources :orders, only:[:new, :index, :show, :create] do
   collection do
    post 'confirm'
    get 'thanks'
   end
  end
 end

 root to: 'public/homes#top'
 get 'about' => 'public/homes#about'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  def full_name
    self.last_name + self.first_name
  end

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + full_name
  end
  
  def active_for_authentication?
    super && (is_active == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  attachment :image

  def add_tax_price
    (self.price * 1.1).round
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum oder_status: { unpaid: 0, deposited: 1, producing: 2, preparation: 3, sent: 4 }

  def full_address
    '〒' + postal_code + ' ' + address
  end

  def itemtotal
    total_amount - postage
  end

  def total_count
   total = 0
	 order_items.each do |order_items|
	  total += order_items.amount
	 end
	 total
	end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum task_status: { pending: 0, waiting: 1, working: 2, completed: 3 }

  def subtotal
    sub_total * amount
  end

  def item_subtotal
    item.add_tax_price * amount
  end
  

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def edit
     @item = Item.find(params[:id])
     @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    @total_price = 0
  end

  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  def after_sign_in_path_for(resource)
   if resource.instance_of?(Admin)
     admin_path
   elsif resource.instance_of?(Customer)
     root_path
   else
     root_path
   end
  end

  def after_sign_out_path_for(resource)
   if resource == :admin
     new_admin_session_path
   elsif resource == :customer
     root_path
   else
     root_path
   end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <nav class="navbar navbar navbar-expand-lg navbar-light bg-light">
     <div class="container">
      <a class="navbar-brand" href="/">LOGO</a>
      <ul class="collapse navbar-collapse">
       <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
         <li class="nav-item">
           <%= link_to "商品一覧", admin_items_path, class:"nav-link text-black" %>
          </button>
         </li>
         <li class="nav-item">
           <%= link_to "会員一覧", admin_customers_path, class:"nav-link text-black" %>
          </button>
         </li>
         <li class="nav-item">
           <%= link_to "注文一覧", admin_path, class:"nav-link text-black" %>
          </button>
         </li>
         <li class="nav-item">
           <%= link_to "ジャンル一覧", admin_genres_path, class:"nav-link text-black" %>
          </button>
         </li>
         <li class="nav-item">
           <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"nav-link text-black" %>
          </button>
         </li>
        <% elsif customer_signed_in? %>
         <li class="nav-item">
           <%= link_to "マイページ", customer_path(current_customer), class:"nav-link text-black" %>
          </button>
         </li>
         <li class="nav-item">
           <%= link_to "商品一覧", items_path, class:"nav-link text-black" %>
          </button>
         </li>
         <li class="nav-item">
           <%= link_to "カート", cart_items_path(current_customer), class:"nav-link text-black" %>
          </button>
         </li>
         <li class="nav-item">
           <%= link_to " ログアウト", destroy_customer_session_path, method: :delete, class:"nav-link text-black" %>
          </button>
         </li>
        <% else %>
         <li class="nav-item">
           <%= link_to "About", about_path, class:"nav-link text-black" %>
         </li>
         <li class="nav-item">
           <%= link_to "商品一覧", items_path, class:"nav-link text-black" %>
         </li>
         <li class="nav-item">
           <%= link_to "新規登録", new_customer_registration_path, class:"nav-link text-black" %>
         </li>
         <li class="nav-item">
           <%= link_to "ログイン", new_customer_session_path, class:"nav-link text-black" %>
         </li>
        <% end %>
       </ul>
      </ul>
     </div>
    </nav>
   </header>
   <p></p>
   <%= yield %>
  </body>
</html>